scratch-org-def: config/project-scratch-def.json
assign-permset: false
permset-name: dreamhouse
run-apex-tests: true
apex-test-format: tap
delete-scratch-org: false
show-scratch-org-url: true
open-path: one/one.app
import-data: false
data-plans:
